In [6]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns


In [7]:
import numpy as np

In [8]:
data = [0,2,4,6]
a = np.array(data)

In [9]:
type(a)

numpy.ndarray

In [10]:
a

array([0, 2, 4, 6])

In [11]:
a.shape

(4,)

In [12]:
a.ndim

1

In [13]:
a.size

4

In [14]:
a.nbytes

32

In [15]:
a.dtype

dtype('int64')

In [17]:
data = [[0.0,2.0,4.0,6.0],[1.0,3.0,5.0,7.0]]
b = np.array(data)

In [18]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.]])

In [19]:
b.shape, b.ndim, b.size, b.nbytes

((2, 4), 2, 8, 64)

In [21]:
c = np.arange(0.0,10.0,1.0)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [22]:
e = np.linspace(0.0,5.0,11)
e

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [23]:
np.empty((4,4))

array([[  6.92171312e-310,   6.92171312e-310,   2.22358789e-317,
          2.47032823e-323],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.02034658e+175],
       [  0.00000000e+000,   0.00000000e+000,   6.12009442e-062,
          0.00000000e+000],
       [  0.00000000e+000,   4.82337723e+228,   0.00000000e+000,
          0.00000000e+000]])

In [24]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [26]:
a = np.array([0,1,2,3])

In [28]:
a, a.dtype

(array([0, 1, 2, 3]), dtype('int64'))

In [29]:
b = np.zeros((2,2), dtype = np.complex64)
b

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]], dtype=complex64)

In [31]:
c = np.arange(0,10,2,dtype = np.float)
c

array([ 0.,  2.,  4.,  6.,  8.])

In [32]:
d = c.astype(dtype = np.int)
d

array([0, 2, 4, 6, 8])